www/emarket/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from views import *


urlpatterns = patterns('',
    url(r'^emarket/sc/add/$',
        ShoppingCartAddView.as_view(),
        name='shopping-cart.add'
    ),

    url(r'^emarket/sc/remove/(?P<sale_id>\d+)$',
        ShoppingCartRemoveView.as_view(),
        name='shopping-cart.remove'),

#    url(r'^vos-adresses-de-livraison/$',
#        DeliveryView.as_view(),
#        name='delivery'),

    url(r'^vos-adresses-de-livraison/$',
        TemplateView.as_view(template_name='mmm-over.html'),
        name='delivery'),

    # Confirm the client everything went fine
    url(r'^checkout-ok/$',
        CheckoutOKClient.as_view(),
        name='checkout_ok.client'),

    url(r'be2bill/notifications/transaction/',
        Be2billNotifTransaction.as_view(),
        name='be2bill.notifications.transaction'),
)

www/mmm/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView

from django.contrib import admin
admin.autodiscover()

from emarket import views as emarket_views
import views


urlpatterns = patterns('',
    url(r'^favicon\.ico$',
        RedirectView.as_view(url=settings.STATIC_URL + 'img/favicon.ico')
    ),

    #Legacy

    url(r'^offrir/$',
        RedirectView.as_view(url=reverse_lazy('order'),
                             permanent=False),
        name='offer'
    ),


    url(r'^$',
        TemplateView.as_view(template_name='homepage.html'),
        name='homepage'
    ),

    url(r'^mon-compte/$',
        RedirectView.as_view(url=reverse_lazy('account/orders'),
                             permanent=False),
        name='account'
    ),

    url(r'^mon-compte/commandes/$',
        views.AccountOrdersView.as_view(),
        name='account/orders'
    ),

    url(r'^mon-compte/commandes/(?P<pk>\d+)/$',
        views.OrderView.as_view(template_name='account/order.html'),
        name='account/order'
    ),

    url(r'^mon-compte/commandes/(?P<pk>\d+)/facture/$',
        views.OrderInvoicePdfView.as_view(template_name='account/order.html'),
        name='account/order/pdf_invoice'
    ),

    url(r'^google5fa0e92da89aaa27\.html$',
        TemplateView.as_view(template_name='google5fa0e92da89aaa27.html')
    ),

    url(r'^landing/madameaime-phyderma/$',
        TemplateView.as_view(template_name='landing/madameaime-phyderma.html'),
        name='landing/madameaime-phyderma'
    ),

    url(r'^comment-ca-marche/$',
        TemplateView.as_view(template_name='how-does-it-work.html'),
        name='how-does-it-work'
    ),

    url(r'^commander/$',
        views.OfferView.as_view(template_name='order.html'),
        name='order'
    ),

    url(r'^qui-sommes-nous/$',
        TemplateView.as_view(template_name='about.html'),
        name='about'
    ),

    url(r'^notre-histoire/$',
        TemplateView.as_view(template_name='story.html'),
        name='story'
    ),

    url(r'^livraison/$',
        TemplateView.as_view(template_name='delivery.html'),
        name='delivery'
    ),

    url(r'^cgv/$',
        TemplateView.as_view(template_name='sales-conditions.html'),
        name='sales-conditions'
    ),

    url(r'^mentions-legales/$',
        TemplateView.as_view(template_name='legal.html'),
        name='legal'
    ),

    # Brands:

    url(r'^marques/$',
        TemplateView.as_view(template_name='brands.html'),
        name='brands'
    ),

    url(r'^marques/jeanne-m/$',
        TemplateView.as_view(template_name='brands/jeanne-m.html'),
        name='brands/jeanne-m'
    ),

    url(r'^marques/jeanne-m/soin-pour-les-pieds/$',
        TemplateView.as_view(template_name='brands/jeanne-m/soin-pour-les-pieds.html'),
        name='brands/jeanne-m/soin-pour-les-pieds'
    ),

    url(r'^marques/au-pays-de-la-fleur-d-oranger/$',
        TemplateView.as_view(template_name='brands/au-pays-de-la-fleur-d-oranger.html'),
        name='brands/au-pays-de-la-fleur-d-oranger'
    ),

    url(r'^marques/au-pays-de-la-fleur-d-oranger/savon-d-invites/$',
        TemplateView.as_view(template_name='brands/au-pays-de-la-fleur-d-oranger/savon-d-invites.html'),
        name='brands/au-pays-de-la-fleur-d-oranger/savon-d-invites'
    ),

    url(r'^marques/newtree/$',
        TemplateView.as_view(template_name='brands/newtree.html'),
        name='brands/newtree'
    ),

    url(r'^marques/oliv/lait-corps-ultra-fondant/$',
        TemplateView.as_view(template_name='brands/oliv/lait-corps-ultra-fondant.html'),
        name='brands/oliv/lait-corps-ultra-fondant'
    ),

    url(r'^marques/secrets-de-miel/$',
        TemplateView.as_view(template_name='brands/secrets-de-miel.html'),
        name='brands/secrets-de-miel'
    ),

    url(r'^marques/sous-l-oranger/$',
        TemplateView.as_view(template_name='brands/sous-l-oranger.html'),
        name='brands/sous-l-oranger'
    ),

    url(r'^marques/comptoir-colonial/$',
        TemplateView.as_view(template_name='brands/comptoir-colonial.html'),
        name='brands/comptoir-colonial'
    ),

    url(r'^marques/teatower/the-a-la-menthe-bio/$',
        TemplateView.as_view(template_name='brands/teatower/the-a-la-menthe-bio.html'),
        name='brands/teatower/the-a-la-menthe-bio'
    ),

    url(r'^marques/phyderma/$',
        TemplateView.as_view(template_name='brands/phyderma.html'),
        name='brands/phyderma'
    ),

    url(r'^marques/phyderma/soin-de-jour-revitalisant/$',
        TemplateView.as_view(template_name='brands/phyderma/soin-de-jour-revitalisant.html'),
        name='brands/phyderma/soin-de-jour-revitalisant'
    ),

    url(r'^marques/phyderma/creme-mains-reparatrice/$',
        TemplateView.as_view(template_name='brands/phyderma/creme-mains-reparatrice.html'),
        name='brands/phyderma/creme-mains-reparatrice'
    ),

    url(r'^marques/dans-le-noir-le-spa/$',
        TemplateView.as_view(template_name='brands/dans-le-noir-le-spa.html'),
        name='brands/dans-le-noir-le-spa'
    ),

    url(r'^marques/le-coin-des-delices/miel-de-citronnier/$',
        TemplateView.as_view(template_name='brands/le-coin-des-delices/miel-de-citronnier.html'),
        name='brands/le-coin-des-delices/miel-de-citronnier'
    ),

    url(r'^marques/le-coin-des-delices/nougat-de-montelimar/$',
        TemplateView.as_view(template_name='brands/le-coin-des-delices/nougat-de-montelimar.html'),
        name='brands/le-coin-des-delices/nougat-de-montelimar'
    ),

    url(r'^marques/sothys/gelee-gommante-visage/$',
        TemplateView.as_view(template_name='brands/sothys/gelee-gommante-visage.html'),
        name='brands/sothys/gelee-gommante-visage'
    ),


    # Boxes:

    url(r'^coffret/$',
        RedirectView.as_view(url=reverse_lazy('boxes/2013-jun'),
                             permanent=False),
        name='boxes'
    ),

    url(r'^coffret/jardin-ete2013/$',
        TemplateView.as_view(template_name='boxes/2013-jun.html'),
        name='boxes/2013-jun'
    ),

    url(r'^coffret/mai-2013/$',
        TemplateView.as_view(template_name='boxes/2013-may.html'),
        name='boxes/2013-may'
    ),

    url(r'^coffret/mars-2013/$',
        TemplateView.as_view(template_name='boxes/2013-mar.html'),
        name='boxes/2013-mar'
    ),

    url(r'^coffret/fevrier-2013/$',
        TemplateView.as_view(template_name='boxes/2013-feb.html'),
        name='boxes/2013-feb'
    ),

    url(r'^coffret/decembre-2012/$',
        TemplateView.as_view(template_name='boxes/2012-dec.html'),
        name='boxes/2012-dec'
    ),


    url(r'^faq/$',
        TemplateView.as_view(template_name='faq.html'),
        name='faq'
    ),

    url(r'^contact/$',
        views.ContactView.as_view(),
        name='contact'
    ),

    url(r'^presse/$',
        TemplateView.as_view(template_name='press.html'),
        name='press'
    ),

    url(r'^jobs/$',
        TemplateView.as_view(template_name='jobs.html'),
        name='jobs'),

    url(r'inscription-sur-newsletter',
        views.NewsletterView.as_view(),
        name='newsletter.add'
    ),

    url(r'^inscription/$',
        views.RegistrationView.as_view(),
        name='register'
    ),

    url(r'^se-connecter/$',
        views.AuthenticationView.as_view(),
        name='login'
    ),

    url(r'mot-de-passe-oublie/$',
        views.RecoverPasswordView.as_view(),
        name='password.recover'
    ),

    url(r'nouveau-mot-de-passe/$',
        views.UpdatePasswordView.as_view(),
        name='password.update'
    ),

    url(r'^votre-panier/$',
        emarket_views.ShoppingCartView.as_view(),
        name='shopping-cart'
    ),

    url(r'^paiement/$',
        emarket_views.PaymentView.as_view(),
        name='payment'
    ),

    url(r'',
        include('emarket.urls', namespace='emarket')
    ),

    url(r'^backoffice/',
        include('mmm_backoffice.urls')
    ),

    url(r'deconnexion/$',
        'django.contrib.auth.views.logout', {'next_page': reverse_lazy('homepage')},
        name='logout'
    ),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

www/emarket/forms.py
# -*- coding: utf8 -*-
from datetime import datetime

from django import forms
from django.conf import settings
from django.forms.formsets import BaseFormSet

from be2bill import PaymentForm

from .models import Address, Order, PromoCode


class AddressModelForm(forms.ModelForm):
    """ Simple ModelForm for Address which excludes country because we're only
    ship our products to France.
    """
    class Meta:
        model = Address
        exclude = ('country',)

    def clean_zip_code(self):
        code = self.cleaned_data.get('zip_code')
        try:
            int(code)
        except ValueError:
            raise forms.ValidationError('Code invalide')
        if len(code) != 5:
            raise forms.ValidationError('Code invalide')
        return code


class BillingForm(AddressModelForm):
    def __init__(self, *args, **kwargs):
        """ Phone isn't required in the Address model but it is for the Billing
        form.
        """
        super(BillingForm, self).__init__(*args, **kwargs)
        self.fields['phone'].required = True


class DeliveryForm(AddressModelForm):

    DELIVERY_PLACES_CHOICES = (
        ('0', 'deliver to billing'),
        ('1', 'deliver to custom'),
    )

    sale_id = forms.IntegerField()

    delivery_place = forms.ChoiceField(widget=forms.RadioSelect,
                            choices=DELIVERY_PLACES_CHOICES)

    message = forms.CharField(widget=forms.widgets.Textarea, required=False)

    def clean(self):
        """ UGLY HACK

        If the address where to deliver the object is the same than the billing
        one, fields are not required. Every field is overriden with a dummy
        value (x@x.xxx).

        Better way to achieve the same result could be:
        - mark all fields from DeliveryForm non-required
        - in every clean() method, raise forms.ValidationError if the field is
          empty and delivery_place is different than the billing address
        """
        cleaned_data = super(DeliveryForm, self).clean()
        delivery_place = cleaned_data.get('delivery_place')
        if delivery_place == '0':
            # Iterate over fields of AddressModelForm, and remove errors
            base = AddressModelForm()
            for field in base.fields:
                if field in self.errors:
                    # remove the error and replace the field value with dummy
                    del self.errors[field]
                    cleaned_data[field] = 'x@x.xxx'
        return cleaned_data


class ToSForm(forms.Form):
    """ Checkboxes for terms of service and to subscribe for emails from our
    partners.
    """
    tos = forms.BooleanField()
    partners = forms.BooleanField(required=False)


class Be2billForm(forms.Form, PaymentForm):
    def __init__(self, fields, *args, **kwargs):
        # Default params
        defaults = {
            'IDENTIFIER': settings.BE2BILL_IDENTIFIER,
            '3DSECURE': 'no'
        }
        # be2bill.PaymentForm ctor
        PaymentForm.__init__(self,
                url=settings.BE2BILL_URL,
                fields=dict(list(defaults.items()) + list(fields.items())))
        # Get fields
        fields = self.get_fields(settings.BE2BILL_PASSWORD)
        # django.forms.Form ctor
        forms.Form.__init__(self, initial=fields, *args, **kwargs)
        # Create fields dynamically for this form
        for key in fields:
            self.fields[key] = forms.CharField()


class PromoCodeForm(forms.Form):
    code = forms.CharField(required=False)

    def __init__(self, user, shopping_cart, **kwargs):
        super(PromoCodeForm, self).__init__(**kwargs)
        self.user = user
        self.shopping_cart = shopping_cart
        # the code is not mandatory
        self.fields['code'].required = False

    def clean_code(self):
        """ The promo code is only valid if:
        - the code exists
        - it is valid (not expired)
        - if it is related to a sale, the client ordered this sale 
        - the client has not an order for this code
        """
        data = self.cleaned_data['code']
        if not data:
            return data
        # get the code
        try:
            promo_code = PromoCode.objects.get(code=data)
        except PromoCode.DoesNotExist:
            raise forms.ValidationError("Ce code n'existe pas")
        if Order.objects.filter(user=self.user.pk, promo_code=promo_code) \
                        .count():
            raise forms.ValidationError('Code déjà utilisé')
        if promo_code.expire and datetime.now() >= promo_code.expire:
            raise forms.ValidationError("Ce code est expiré")
        if promo_code.sale and promo_code.sale not in self.shopping_cart:
            raise forms.ValidationError('Code invalide')
        return data

www/mmm/forms.py
from django import forms

from .models import PasswordRecovery, User
import models


class RegistrationForm(forms.ModelForm):
    password_repeat = forms.CharField(widget = forms.PasswordInput)

    def clean_password_repeat(self):
        password = self.cleaned_data.get('password')
        password_repeat = self.cleaned_data.get('password_repeat')

        if password and password_repeat and password != password_repeat:
            raise forms.ValidationError("Passwords don't match")

        return self.cleaned_data

    def save(self):
        return models.User.objects.create_user(
            self.cleaned_data.get('email'),
            self.cleaned_data.get('password')
        )

    class Meta:
        model = models.User
        fields = ('email', 'password')

class NewsletterForm(forms.ModelForm):
    class Meta:
        model = models.Newsletter
        exclude = ('date', 'active')


class RecoverPasswordForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        cleaned_data = self.cleaned_data
        if User.objects.filter(email=cleaned_data.get('email')).count() != 1:
            raise forms.ValidationError('unknown email')
        return cleaned_data['email']


class UpdatePasswordForm(forms.Form):

    password = forms.CharField(widget=forms.PasswordInput())
    confirm = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, mail, secret, *args, **kwargs):
        self.mail = mail
        self.secret = secret
        super(UpdatePasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm(self):
        cleaned_data = self.cleaned_data
        if cleaned_data.get('password') != cleaned_data.get('confirm'):
            raise forms.ValidationError('confirm and password must match')
        return cleaned_data['confirm']

    def clean(self):
        try:
            user = User.objects.get(email=self.mail)
        except User.DoesNotExist:
            raise forms.ValidationError('invalid user')

        # Get the last 10 items from PasswordRecovery (to avoid that someone
        # asks for 1000000 new passwords and tries to bruteforce)
        recover = PasswordRecovery.objects.filter(user=user).order_by('-date')
        for entry in recover:
            if entry.secret == self.secret:
                # update password
                user.set_password(self.cleaned_data['password'])
                user.save()
                # remove
                PasswordRecovery.objects.filter(user=user).delete()
                return self.cleaned_data
        raise forms.ValidationError('invalid mail or secret')

www/mmm/templates/emarket/delivery-input.html
<div class="control-group{% if field.errors %} error{% endif %}">
  <label class="control-label" for="{{field.id_for_label}}">{{field_name}}</label>
  <div class="controls">
    {% if field.errors and display_error_messages %}
    <span class="help-block">{{field.errors.as_text}}</span>
    {% endif %}
    <input type="{{field_type|default:"text"}}" class="input-xlarge" name="{{field.html_name}}" id="{{field.id_for_label}}" value="{{field.value|default_if_none:""}}" />
  </div>
</div>

www/mmm/templates/emarket/delivery.html
{% extends "mmm/skeleton.html" %}
{% block head_title %}Livraison de votre commande{% endblock %}
{% block meta_description %}Choisissez les points de livraison où seront envoyés vos coffrets{% endblock %}
{% block mmm_content %}
<div id="checkout-delivery">
  <form class="form form-horizontal" method="post" action="{% url 'emarket:delivery' %}">
    {% csrf_token %}

    {% if tos_form.tos.errors %}
    <div class="alert alert-error">
      N'oubliez pas de lire et d’accepter les conditions générales de vente !
    </div>
    {% endif %}

    <div class="row-fluid">
      <div class="span6">
	<fieldset>
	  <legend>Mes informations de facturation</legend>
	  <div class="group">
	    {% include "emarket/delivery-input.html" with field_name="Prénom *" field=billing_form.firstname %}
	    {% include "emarket/delivery-input.html" with field_name="Nom *" field=billing_form.lastname %}
	    {% include "emarket/delivery-input.html" with field_name="Email *" field_type="email" field=billing_form.email %}
	    {% include "emarket/delivery-input.html" with field_name="Adresse *" field=billing_form.address %}
	    {% include "emarket/delivery-input.html" with field_name="Complément d'adresse" field=billing_form.additional %}
	    {% include "emarket/delivery-input.html" with field_name="Code postal *" field=billing_form.zip_code %}
	    {% include "emarket/delivery-input.html" with field_name="Ville *" field=billing_form.city %}
	    {% include "emarket/delivery-input.html" with field_name="Téléphone *" field=billing_form.phone %}
	  </div> <!-- group -->
	</fieldset>
      </div> <!-- span6 -->

      <div class="span6">
	<fieldset>
	  <legend>Où sera livré le coffret Madame Aime</legend>
	  {{delivery_formset.management_form}}
	  {% for form in delivery_formset %}
	  <div class="product">

	    {{form.sale_id.as_hidden}}

	    <label class="radio">
	      <input class="receiver-addr-toggle" type="radio" name="{{form.delivery_place.html_name}}" value="0" {% if not form.delivery_place.value or form.delivery_place.value == "0" %}checked {% endif %}/>
	      Livrer le coffret à mon adresse de facturation
	    </label>
	    <label class="radio">
	      <input class="receiver-addr-toggle" type="radio" name="{{form.delivery_place.html_name}}" value="1" {% if form.delivery_place.value == "1" %}checked {% endif %}/>
	      Je souhaite une livraison directement chez la personne
	    </label>

	    <div class="receiver-addr" {% if not form.delivery_place.value or form.delivery_place.value == "0" %} style="display:none;"{% endif %}>
	      {% include "emarket/delivery-input.html" with field_name="Prénom *" field=form.firstname %}
	      {% include "emarket/delivery-input.html" with field_name="Nom *" field=form.lastname %}
	      {% include "emarket/delivery-input.html" with field_name="Email" field=form.email %}
	      {% include "emarket/delivery-input.html" with field_name="Adresse *" field=form.address %}
	      {% include "emarket/delivery-input.html" with field_name="Complément d'adresse" field=form.additional %}
	      {% include "emarket/delivery-input.html" with field_name="Code postal *" field=form.zip_code %}
	      {% include "emarket/delivery-input.html" with field_name="Ville *" field=form.city %}
	      {% include "emarket/delivery-input.html" with field_name="Téléphone" field=form.phone %}
	    </div>

      {% comment %}
      <!-- REMOVE FORM TO ADD A CUSTOM MESSAGE, BECAUSE ADS DOESN'T SUPPORT IT EASILY -->
      <div class="control-group{% if form.message.errors %} error{% endif %}">
        <label class="control-label" for="{{form.message.id_for_label}}">Message personnalisé</label>
        <div class="controls">
          {% if form.message.errors and display_error_messages %}
          <span class="help-block">{{form.message.errors.as_text}}</span>
          {% endif %}
          <textarea name="{{form.message.html_name}}" id="{{form.message.id_for_label}}">{{form.message.value|default_if_none:""}}</textarea>
        </div>
      </div>
      {% endcomment %}

	  </div>
	  {% endfor %}
	</fieldset>
      </div>
    </div> <!-- row fluid -->

    <div class="validate">
      <label class="checkbox">
	<input type="checkbox" name="{{tos_form.tos.html_name}}" {% if tos_form.tos.value %}checked {% endif %}/> J'ai lu et j'accepte les <a href="{% url 'sales-conditions' %}">conditions générales de vente</a>
      </label>
      <label class="checkbox">
	<input type="checkbox" name="{{tos_form.partners.html_name}}" {% if tos_form.partners.value %}checked {% endif %}/> J'accepte de recevoir des bons plans de la part des partenaires de Madame Aime
      </label>
      <button type="submit" class="btn-link shiny">Valider</button>
    </div>
  </form>
</div>
{% endblock %}

www/mmm/templates/emarket/shopping-cart.html
{% extends "mmm/skeleton.html" %}
{% block head_title %}Votre panier - Madame Aime{% endblock %}
{% block meta_description %}Madame Aime est un moyen facile de composer son panier de cadeaux pour se faire plaisir ou faire plaisir à ses proches{% endblock %}
{% block mmm_content %}
<table id="checkout-cart">
  <thead>
    <tr>
      <th class="first"></th>
      <th class="second">Description</th>
      <th class="third"></th>
      <th class="fourth">Prix</th>
      <th class="fifth"></th>
    </tr>
  </thead>
  <tbody>
    {% for object in objects %}
    <tr>
      <td class="thumb"></td>
      <td class="info">
	<b class="name">{{object.product.name}}</b><br />
        <span class="description">
	  {{object.shopping_cart_description|safe|linebreaks}}
	</span>
      </td>
      <td></td>
      <td class="price">
	<span class="value">{{object.price}} €</span><br />
	<span class="shipping">livraison incluse</span>
      </td>
      <td class="delete">
	<form method="post" action="{% url 'emarket:shopping-cart.remove' sale_id=object.pk %}">
	  {% csrf_token %}
          <button type="submit" class="btn-link shiny">Supprimer</button>
        </form>
      </td>
    </tr>
    {% endfor %}

    {% if objects %}
    <tr>
      <td>&nbsp;</td>
      <td class="info"><b>Code promo</b></td>
      <td colspan="2">
        <form method="post" action="{% url 'shopping-cart' %}">
          {% csrf_token %}
          <div class="control-group{% if form.code.errors %} error{% endif %}">
            <br />
            {% if form.code.errors %}
            <span class="help-block">{{form.code.errors.as_text}}</span>
            {% endif %}
            <input type="text" class="input-xlarge" name="{{form.code.html_name}}" id="{{form.code.id_for_label}}" value="{{form.code.value|default_if_none:""}}" />
            <button style="display:inline; border:none; background-color:#fff;" type="submit"><img src="{{STATIC_URL}}/img/ok_btn.png" /></button>
          </div>
        </form>
      </td>
    </tr>
    {% endif %}

  </tbody>
  <tfoot>
    <tr>
      <td class="add" rowspan="2" colspan="2"><a href="{% url 'offer' %}">Ajouter un coffret à ma commande</a></td>
      <td class="total-label">Total</td>
      <td class="total-value">
        <span class="value">{{total_price}} €</span><br />
        <span class="shipping">frais de port inclus</span>
      </td>
      <td rowspan="2" class="validate">
        <a href="{% url 'emarket:delivery' %}">
          <img src="{{ STATIC_URL }}img/checkout/validate.png" alt="Valider" />
        </a>
      </td>
    </tr>
    <tr>
      <td class="vat-label">Dont TVA</td>
      <td class="vat-value">{{charges|floatformat:2}}€</td>
    </tr>
  </tfoot>
</table>

<section id="cart-upsale">
  <h2>Nous vous proposons également :</h2>
  <div class="products clearfix">
    <div>
      <img src="{{ STATIC_URL }}img/checkout/upsale/1.png?0" alt="" />
      <h4>Coffret MadameAime by Vivolta</h4>
      <div class="bottom">
        <p class="price">
          16,90€
        </p>
        <p class="delivery">
          livraison incluse
        </p>
        <form method="post" action="{% url 'emarket:shopping-cart.add' %}">
          {% csrf_token %}
          <input type="hidden" name="sale_id" value="15" />
          <input type="image" src="{{ STATIC_URL }}img/checkout/upsale/add.png" alt="Commander"/>
        </form>
      </div>
    </div>

    <div>
      <img src="{{ STATIC_URL }}img/checkout/upsale/2.png?0" alt="" />
      <h4>Coffret Mon Jardin été</h4>
      <div class="bottom">
        <p class="price">
          24,90€
        </p>
        <p class="delivery">
          livraison incluse
        </p>
        <form method="post" action="{% url 'emarket:shopping-cart.add' %}">
          {% csrf_token %}
          <input type="hidden" name="sale_id" value="18" />
          <input type="image" src="{{ STATIC_URL }}img/checkout/upsale/add.png" alt="Commander"/>
        </form>
      </div>
    </div>

    <div>
      <img src="{{ STATIC_URL }}img/checkout/upsale/3.png?0" alt="" />
      <h4>PACK 2 COFFRETS MON JARDIN</h4>
      <p class="details">
        Coffret Mon Jardin Été<br />
        + Coffret Mon Jardin Rentrée
      </p>
      <div class="bottom">
        <p class="price">
          44,80€ les 2 coffrets
        </p>
        <p class="delivery">
          livraison incluse
        </p>
        <form method="post" action="{% url 'emarket:shopping-cart.add' %}">
          {% csrf_token %}
          <input type="hidden" name="sale_id" value="16" />
          <input type="image" src="{{ STATIC_URL }}img/checkout/upsale/add.png" alt="Commander"/>
        </form>
      </div>
    </div>

    <div>
      <img src="{{ STATIC_URL }}img/checkout/upsale/4.png?0" alt="" />
      <h4>PACK 2 COFFRETS BEAUTÉ & JARDIN</h4>
      <p class="details">
        Coffret Mon Jardin Été<br />
        + MadameAime by Vivolta
      </p>
      <div class="bottom">
        <p class="price">
          39,80€ les 2 coffrets
        </p>
        <p class="delivery">
          livraison incluse
        </p>
        <form method="post" action="{% url 'emarket:shopping-cart.add' %}">
          {% csrf_token %}
          <input type="hidden" name="sale_id" value="17" />
          <input type="image" src="{{ STATIC_URL }}img/checkout/upsale/add.png" alt="Commander"/>
        </form>
      </div>
    </div>
  </div>
</section>

<section id="index-security" class="row-fluid">
  <div class="span4">
    <img src="{{ STATIC_URL }}img/homepage/lock.png" alt=""/>
    Paiement sécurisé
  </div>
  <div class="span4">
    <img src="{{ STATIC_URL }}img/homepage/truck.png" alt=""/>
    Livraison incluse
  </div>
  <div class="span4">
    <img src="{{ STATIC_URL }}img/homepage/phone.png" alt=""/>
    01.02.03.04.05
  </div>
</section>
{% endblock %}